<?php

namespace Database\Seeders;

use App\Models\Company;
use App\Models\Landing;
use App\Models\Link;
use App\Models\Role;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

/**
 * Seeder to import data from MongoDB archive export.
 * Uses JSON files generated by scripts/parse_mongo_archive.py
 */
class MongoImportSeeder extends Seeder
{
    /**
     * Maps MongoDB _id to new UUID.
     */
    private array $idMap = [
        'users' => [],
        'companies' => [],
        'landings' => [],
        'roles' => [],
    ];

    private string $importDir = 'storage/mongo_import';

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->command->info('Starting MongoDB import...');

        // Create default roles first
        $this->createRoles();

        // Import in order of dependencies
        $this->importUsers();
        $this->importCompanies();
        $this->importLandings();
        $this->importLinks();

        // Update relationships after all imports
        $this->updateRelationships();

        $this->command->info('MongoDB import completed successfully!');
    }

    /**
     * Create default roles.
     */
    private function createRoles(): void
    {
        $roles = [
            ['name' => 'Root', 'type' => 'root'],
            ['name' => 'Admin', 'type' => 'admin'],
            ['name' => 'User', 'type' => 'user'],
        ];

        foreach ($roles as $role) {
            $created = Role::firstOrCreate(['type' => $role['type']], $role);
            // Map common role names
            if ($role['type'] === 'root') {
                $this->idMap['roles']['root'] = $created->id;
            }
            if ($role['type'] === 'admin') {
                $this->idMap['roles']['60e60c8632bff4267d1c4792'] = $created->id;
            }
            if ($role['type'] === 'user') {
                $this->idMap['roles']['user'] = $created->id;
            }
        }

        $this->command->info('Created roles');
    }

    /**
     * Import users from JSON.
     */
    private function importUsers(): void
    {
        $users = $this->loadJson('users.json');
        $count = 0;
        $userRole = Role::where('type', 'user')->first();
        $adminRole = Role::where('type', 'admin')->first();
        $rootRole = Role::where('type', 'root')->first();

        foreach ($users as $userData) {
            $mongoId = $userData['_id'];

            // Skip if already exists
            if (User::where('mongo_id', $mongoId)->exists()) {
                $existing = User::where('mongo_id', $mongoId)->first();
                $this->idMap['users'][$mongoId] = $existing->id;
                continue;
            }

            // Clean email
            $email = strtolower(trim($userData['email'] ?? ''));
            if (empty($email) || User::where('email', $email)->exists()) {
                continue;
            }

            // Clean username
            $username = $this->sanitizeUsername($userData['username'] ?? '');
            if (empty($username) || User::where('username', $username)->exists()) {
                $username = $username . '_' . substr($mongoId, -4);
            }

            try {
                $user = User::create([
                    'first_name' => $userData['first_name'] ?? null,
                    'last_name' => $userData['last_name'] ?? null,
                    'name' => ($userData['first_name'] ?? '') . ' ' . ($userData['last_name'] ?? ''),
                    'username' => $username,
                    'email' => $email,
                    'password' => $userData['password'] ?? Hash::make('12345678'),
                    'verified_at' => isset($userData['verified_at']) ? $this->parseDate($userData['verified_at']) : null,
                    'verification_code' => $userData['verification_code'] ?? null,
                    'mautic_id' => $userData['mautic_id'] ?? null,
                    'settings' => $userData['settings'] ?? ['autoSave' => true],
                    'mongo_id' => $mongoId,
                    'created_at' => $this->parseDate($userData['created_at'] ?? null),
                    'updated_at' => $this->parseDate($userData['updated_at'] ?? null),
                ]);

                // Assign role: root_linkea gets root, admins get admin, others get user
                $isRoot = $userData['username'] === 'root_linkea';
                $isAdmin = !$isRoot && isset($userData['role_id']) &&
                    in_array('60e60c8632bff4267d1c4792', (array)$userData['role_id']);

                if ($isRoot) {
                    $user->roles()->attach($rootRole->id);
                } elseif ($isAdmin) {
                    $user->roles()->attach($adminRole->id);
                } else {
                    $user->roles()->attach($userRole->id);
                }

                $this->idMap['users'][$mongoId] = $user->id;
                $count++;
            } catch (\Exception $e) {
                $this->command->warn("Failed to import user {$email}: {$e->getMessage()}");
            }
        }

        $this->command->info("Imported {$count} users");
    }

    /**
     * Import companies from JSON.
     */
    private function importCompanies(): void
    {
        $companies = $this->loadJson('companies.json');
        $count = 0;

        foreach ($companies as $companyData) {
            $mongoId = $companyData['_id'];

            // Skip if already exists
            if (Company::where('mongo_id', $mongoId)->exists()) {
                $existing = Company::where('mongo_id', $mongoId)->first();
                $this->idMap['companies'][$mongoId] = $existing->id;
                continue;
            }

            // Get owner_id mapping
            $ownerMongoId = $companyData['owner_id'] ?? null;
            $ownerId = $ownerMongoId ? ($this->idMap['users'][$ownerMongoId] ?? null) : null;

            // Find owner by company_id reference in users
            if (!$ownerId) {
                $owner = User::where('mongo_id', $ownerMongoId)->first();
                if (!$owner) {
                    // Try to find user with this company
                    $users = $this->loadJson('users.json');
                    foreach ($users as $u) {
                        if (($u['company_id'] ?? '') === $mongoId) {
                            $owner = User::where('mongo_id', $u['_id'])->first();
                            break;
                        }
                    }
                }
                $ownerId = $owner?->id;
            }

            try {
                $slug = $this->sanitizeSlug($companyData['slug'] ?? Str::slug($companyData['name'] ?? 'company'));

                $company = Company::updateOrCreate(
                    ['slug' => $slug],
                    [
                        'name' => $companyData['name'] ?? 'Sin nombre',
                        'owner_id' => $ownerId,
                        'mongo_id' => $mongoId,
                        'created_at' => $this->parseDate($companyData['created_at'] ?? null),
                        'updated_at' => $this->parseDate($companyData['updated_at'] ?? null),
                    ]
                );

                $this->idMap['companies'][$mongoId] = $company->id;
                $count++;
            } catch (\Exception $e) {
                $this->command->warn("Failed to import company: {$e->getMessage()}");
            }
        }

        $this->command->info("Imported {$count} companies");
    }

    /**
     * Import landings from JSON.
     */
    private function importLandings(): void
    {
        $landings = $this->loadJson('landings.json');
        $count = 0;

        foreach ($landings as $landingData) {
            $mongoId = $landingData['_id'];

            // Skip if already exists
            if (Landing::where('mongo_id', $mongoId)->exists()) {
                $existing = Landing::where('mongo_id', $mongoId)->first();
                $this->idMap['landings'][$mongoId] = $existing->id;
                continue;
            }

            // Get company_id mapping
            $companyMongoId = $landingData['company_id'] ?? null;
            $companyId = $companyMongoId ? ($this->idMap['companies'][$companyMongoId] ?? null) : null;

            // Get user_id - find user with this company
            $userId = null;
            if ($companyMongoId) {
                $users = $this->loadJson('users.json');
                foreach ($users as $u) {
                    if (($u['company_id'] ?? '') === $companyMongoId) {
                        $userId = $this->idMap['users'][$u['_id']] ?? null;
                        break;
                    }
                }
            }

            // Sanitize domain_name for URLs (preserves . _ - but removes special chars like ¥)
            $domainName = $this->sanitizeSlugForUrl($landingData['domain_name'] ?? $landingData['slug'] ?? '');
            if (empty($domainName)) {
                $domainName = 'landing-' . substr($mongoId, -8);
            }

            // Check for duplicate domain_name
            if (Landing::where('domain_name', $domainName)->exists()) {
                $domainName = $domainName . '-' . substr($mongoId, -4);
            }

            // Process logo
            $logo = $landingData['logo'] ?? null;
            if (is_array($logo)) {
                // Keep the logo structure but ensure paths are stored correctly
                $logo = [
                    'image' => $logo['image'] ?? null,
                    'thumb' => $logo['thumb'] ?? null,
                ];
            }

            try {
                // Sanitize slug for URLs (preserves . _ - but removes special chars)
                $slug = $this->sanitizeSlugForUrl($landingData['slug'] ?? $domainName);

                // Process template_config with legacy defaults
                // Keep template_config.title and template_config.subtitle as-is (this is the correct structure)
                $templateConfig = $this->processLegacyTemplateConfig($landingData['template_config'] ?? []);

                $landing = Landing::create([
                    'name' => $landingData['name'] ?? $domainName, // Internal name
                    'slug' => $slug,
                    'domain_name' => $domainName,
                    'logo' => $logo,
                    'verify' => $landingData['verify'] ?? false,
                    'company_id' => $companyId,
                    'user_id' => $userId,
                    'template_config' => $templateConfig, // Contains title & subtitle
                    'options' => $landingData['options'] ?? [],
                    'mongo_id' => $mongoId,
                    'created_at' => $this->parseDate($landingData['created_at'] ?? null),
                    'updated_at' => $this->parseDate($landingData['updated_at'] ?? null),
                ]);

                $this->idMap['landings'][$mongoId] = $landing->id;
                $count++;
            } catch (\Exception $e) {
                $this->command->warn("Failed to import landing {$domainName}: {$e->getMessage()}");
            }
        }

        $this->command->info("Imported {$count} landings");
    }

    /**
     * Import links from JSON.
     */
    private function importLinks(): void
    {
        $links = $this->loadJson('links.json');
        $count = 0;
        $skippedDeleted = 0;

        foreach ($links as $linkData) {
            $mongoId = $linkData['_id'];

            // Skip soft-deleted links from MongoDB (they have deleted_at set)
            if (!empty($linkData['deleted_at'])) {
                $skippedDeleted++;
                continue;
            }

            // Skip if already exists
            if (Link::where('mongo_id', $mongoId)->exists()) {
                continue;
            }

            // Get landing_id mapping
            $landingMongoId = $linkData['landing_id'] ?? null;
            $landingId = $landingMongoId ? ($this->idMap['landings'][$landingMongoId] ?? null) : null;

            if (!$landingId) {
                // Try to find landing by mongo_id
                $landing = Landing::where('mongo_id', $landingMongoId)->first();
                $landingId = $landing?->id;
            }

            if (!$landingId) {
                continue; // Skip orphan links
            }

            // Map legacy type names
            $type = $linkData['type'] ?? 'button';
            $typeMap = [
                'button' => 'link',
                'heading' => 'header',
            ];
            $type = $typeMap[$type] ?? $type;

            try {
                Link::create([
                    'landing_id' => $landingId,
                    'text' => $linkData['text'] ?? '',
                    'link' => $linkData['link'] ?? '',
                    'slug' => is_string($linkData['slug'] ?? null) ? $linkData['slug'] : null,
                    'state' => $linkData['state'] ?? true,
                    'type' => $type,
                    'group' => $linkData['group'] ?? 'links',
                    'order' => $linkData['order'] ?? 0,
                    'icon' => $linkData['icon'] ?? null,
                    'options' => is_array($linkData['options'] ?? null) ? $linkData['options'] : null,
                    'visited' => $linkData['visited'] ?? 0,
                    'mongo_id' => $mongoId,
                    'created_at' => $this->parseDate($linkData['created_at'] ?? null),
                    'updated_at' => $this->parseDate($linkData['updated_at'] ?? null),
                ]);

                $count++;
            } catch (\Exception $e) {
                $this->command->warn("Failed to import link: {$e->getMessage()}");
            }
        }

        $this->command->info("Imported {$count} links (skipped {$skippedDeleted} deleted)");
    }

    /**
     * Update relationships that couldn't be set during initial import.
     */
    private function updateRelationships(): void
    {
        // Update user company_id
        $users = $this->loadJson('users.json');
        foreach ($users as $userData) {
            $companyMongoId = $userData['company_id'] ?? null;
            if (!$companyMongoId) continue;

            $companyId = $this->idMap['companies'][$companyMongoId] ?? null;
            if (!$companyId) {
                $company = Company::where('mongo_id', $companyMongoId)->first();
                $companyId = $company?->id;
            }

            if ($companyId) {
                User::where('mongo_id', $userData['_id'])->update(['company_id' => $companyId]);
            }
        }

        $this->command->info('Updated relationships');
    }

    /**
     * Load JSON file from import directory.
     */
    private function loadJson(string $filename): array
    {
        $path = base_path($this->importDir . '/' . $filename);

        if (!file_exists($path)) {
            $this->command->warn("File not found: {$filename}");
            return [];
        }

        $content = file_get_contents($path);
        return json_decode($content, true) ?? [];
    }

    /**
     * Parse date from MongoDB format.
     */
    private function parseDate($date): ?string
    {
        if (empty($date)) return null;

        try {
            if (is_string($date)) {
                return \Carbon\Carbon::parse($date)->toDateTimeString();
            }
        } catch (\Exception $e) {
            return null;
        }

        return null;
    }

    /**
     * Sanitize username.
     */
    private function sanitizeUsername(string $username): string
    {
        // Remove special chars, lowercase
        $username = strtolower(trim($username));
        $username = preg_replace('/[^a-z0-9_.-]/', '', $username);
        $username = preg_replace('/\.+$/', '', $username); // Remove trailing dots

        return $username ?: 'user_' . Str::random(6);
    }

    /**
     * Sanitize slug/domain_name for companies (used internally).
     * Allows dots (.) for compatibility with legacy slugs like "mambar_.s"
     */
    private function sanitizeSlug(string $slug): string
    {
        // Lowercase, remove special chars except hyphens, underscores and dots
        $slug = strtolower(trim($slug));
        $slug = preg_replace('/[^a-z0-9_.-]/', '', $slug);
        $slug = preg_replace('/-+/', '-', $slug); // Remove multiple hyphens
        $slug = trim($slug, '-');

        return $slug ?: 'page-' . Str::random(6);
    }

    /**
     * Sanitize slug/domain_name for URLs.
     * - Converts accented chars to ASCII (ñ->n, á->a, etc.)
     * - Removes special symbols (¥, ©, etc.) instead of transliterating
     * - Preserves dots (.) for legacy slugs like "mambar_.s"
     */
    private function sanitizeSlugForUrl(string $slug): string
    {
        // Lowercase and trim
        $slug = mb_strtolower(trim($slug));

        // Convert accented letters to ASCII (á->a, ñ->n, etc.)
        // but NOT symbols like ¥ which would become "yenn"
        $transliterations = [
            'á' => 'a',
            'à' => 'a',
            'ä' => 'a',
            'â' => 'a',
            'ã' => 'a',
            'é' => 'e',
            'è' => 'e',
            'ë' => 'e',
            'ê' => 'e',
            'í' => 'i',
            'ì' => 'i',
            'ï' => 'i',
            'î' => 'i',
            'ó' => 'o',
            'ò' => 'o',
            'ö' => 'o',
            'ô' => 'o',
            'õ' => 'o',
            'ú' => 'u',
            'ù' => 'u',
            'ü' => 'u',
            'û' => 'u',
            'ñ' => 'n',
            'ç' => 'c',
        ];
        $slug = strtr($slug, $transliterations);

        // Remove any non-URL chars (keep a-z, 0-9, _, -, .)
        $slug = preg_replace('/[^a-z0-9_.-]/', '', $slug);

        // Clean up multiple consecutive special chars
        $slug = preg_replace('/-{2,}/', '-', $slug);
        $slug = preg_replace('/\.{2,}/', '.', $slug);
        $slug = preg_replace('/_{2,}/', '_', $slug);

        // Trim special chars from start/end
        $slug = trim($slug, '-_.');

        return $slug ?: 'page-' . Str::random(6);
    }

    /**
     * Process legacy template_config with migration defaults.
     * Sets legacy-specific values to preserve original appearance.
     */
    private function processLegacyTemplateConfig(array $config): array
    {
        // Legacy landings: flat avatar (no floating effect)
        $config['image_floating'] = false;

        // Legacy landings: don't show URL subtexts
        $config['showLinkSubtext'] = false;

        // Legacy landings: always showed title and subtitle (no toggles existed)
        // Set to true by default so imported landings display correctly
        if (!isset($config['showTitle'])) {
            $config['showTitle'] = true;
        }
        if (!isset($config['showSubtitle'])) {
            $config['showSubtitle'] = true;
        }

        // Ensure header config exists with legacy defaults
        if (!isset($config['header'])) {
            $config['header'] = [];
        }
        $config['header']['avatarFloating'] = false;

        // Ensure buttons config exists and set size to compact (legacy default)
        if (!isset($config['buttons'])) {
            $config['buttons'] = [];
        }
        if (!isset($config['buttons']['size'])) {
            $config['buttons']['size'] = 'compact';
        }

        return $config;
    }
}
